# Instance variables vs Class variables in Python........

class Employee:
    # this is a class  variable are same every employe because employer are change but company name don't change....
    companyName = "Apple"  # class variable...
    def __init__(self,name):
        self.name = name     # this is a instance  variable......
        self.raise_ammount = 0.02  # this is a instance  variable......
    def showDetails(self):
        print(f"The employee name is: {self.name} and the raise_ammount is: {self.raise_ammount} And the company Name is: {self.companyName}" )

# Employee.showDetails(ep)   # direct method to call...

ep = Employee("Aditya")
ep.showDetails()

ep1 = Employee("Parth")
ep1.showDetails()
